# Generated by Django 4.1.1 on 2022-10-04 13:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
