# Generated by Django 4.1.1 on 2022-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='clubselected',
            field=models.CharField(choices=[('1', 'IEEE'), ('2', 'ACM'), ('3', 'ROTARACT CLUB'), ('4', 'IE'), ('5', 'ISTE'), ('6', 'IET')], default='IEEE', max_length=16),
        ),
    ]
