# Generated by Django 4.1.1 on 2022-10-08 06:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='deadlin',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
