# Generated by Django 4.1.1 on 2022-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_subtasks_deadlin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='socialmedia',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Whatsapp', 'Whatsapp'), ('LinkedIn', 'LinkedIn')], default='LinkedIn', max_length=9),
        ),
    ]
