# Generated by Django 4.1.1 on 2023-07-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_task_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
